version: "3"
services:
  postgres:
    build: ./postgres
  api:
    build: ./api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    network_mode: "host"
    environment:
      DATABASE_URL: "postgres://postgres:123@localhost:5432/flask_tasks" 
  janitor:
    build: ./janitor
    depends_on:
      - postgres
    network_mode: "host"
    environment:
      DATABASE_URL: "postgres://postgres:123@localhost:5432/flask_tasks"
  handler:
    build: ./handler
    depends_on:
      - postgres
    network_mode: "host"
    environment:
      DATABASE_URL: "postgres://postgres:123@localhost:5432/flask_tasks"