app = "flask-tasks-handler"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "brenopelegrin/flask-tasks-handler:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
